vim.pack.add { 'https://github.com/folke/which-key.nvim' }

-- Group names must be plain words (LazyVim-style). Bracketed mnemonics like
-- `[B]uffer` break which-key's desc pattern matching, so icons never appear.
-- Extra rules: LazyVim gets snacks/plugin icons via lazy.nvim; we don't, so
-- cover leftover descs with patterns (checked before built-in rules).
require('which-key').setup {
  delay = 0,
  icons = {
    mappings = vim.g.have_nerd_font,
    rules = {
      { pattern = 'grep', icon = ' ', color = 'green' },
      { pattern = 'command', icon = ' ', color = 'orange' },
      { pattern = 'project', icon = ' ', color = 'blue' },
      { pattern = 'mark', icon = '󰃀 ', color = 'yellow' },
      { pattern = 'jump', icon = '󰒓 ', color = 'orange' },
      { pattern = 'register', icon = '󰍛 ', color = 'yellow' },
      { pattern = 'autocmd', icon = '󰆍 ', color = 'cyan' },
      { pattern = 'icon', icon = '󰊕 ', color = 'yellow' },
      { pattern = 'man page', icon = ' ', color = 'azure' },
      { pattern = 'colorscheme', icon = '󰏘 ', color = 'purple' },
      { pattern = 'lazygit', icon = ' ', color = 'orange' },
      { pattern = 'hunk', icon = '󰊢 ', color = 'green' },
      { pattern = 'undo', icon = '󰕌 ', color = 'yellow' },
      { pattern = 'resume', icon = '󰐊 ', color = 'green' },
      { pattern = 'replace', icon = '󰛔 ', color = 'blue' },
      { pattern = 'rename', icon = '󰑕 ', color = 'yellow' },
      { pattern = 'mason', icon = '󱌣 ', color = 'blue' },
      { pattern = 'pack', icon = '󰏖 ', color = 'yellow' },
      { pattern = 'todo', icon = '󰄱 ', color = 'yellow' },
      { pattern = 'flash', icon = '⚡', color = 'yellow' },
      { pattern = 'location', icon = '󰍉 ', color = 'green' },
      { pattern = 'quickfix', icon = '󱖫 ', color = 'red' },
      { pattern = 'symbol', icon = ' ', color = 'cyan' },
      { pattern = 'reference', icon = '󰈇 ', color = 'cyan' },
      { pattern = 'inspect', icon = '󱔁 ', color = 'cyan' },
      { pattern = 'scratch', icon = '󰩬 ', color = 'purple' },
      { pattern = 'pin', icon = '󰐃 ', color = 'azure' },
      { pattern = 'delete', icon = '󰧧 ', color = 'red' },
      { pattern = 'explorer', icon = '󰙅 ', color = 'green' },
      { pattern = 'recent', icon = ' ', color = 'cyan' },
      { pattern = 'history', icon = ' ', color = 'azure' },
      { pattern = 'highlight', icon = '󰸱 ', color = 'yellow' },
      { pattern = 'keymap', icon = ' ', color = 'green' },
      { pattern = 'help', icon = '󰋖 ', color = 'cyan' },
      { pattern = 'blame', icon = '󰊢 ', color = 'red' },
      { pattern = 'stash', icon = '󰋚 ', color = 'yellow' },
      { pattern = 'browse', icon = '󰖟 ', color = 'blue' },
      { pattern = 'log', icon = '󰜘 ', color = 'green' },
      { pattern = 'status', icon = '󰊢 ', color = 'red' },
      { pattern = 'diff', icon = '󰦓 ', color = 'green' },
      { pattern = 'stage', icon = '󰐖 ', color = 'green' },
      { pattern = 'reset', icon = '󰑓 ', color = 'red' },
      { pattern = 'preview', icon = '󰈈 ', color = 'blue' },
      { pattern = 'pairs', icon = '󰅪 ', color = 'yellow' },
      { pattern = 'save', icon = '󰆓 ', color = 'green' },
      { pattern = 'pick', icon = '󰒓 ', color = 'cyan' },
      { pattern = 'lsp', icon = ' ', color = 'orange' },
      { pattern = 'action', icon = ' ', color = 'orange' },
      { pattern = 'hydra', icon = ' ', color = 'blue' },
      { pattern = 'noice', icon = '󰈸', color = 'orange' },
      { pattern = 'dismiss', icon = '󰅖 ', color = 'red' },
      { pattern = 'undotree', icon = '󰕌 ', color = 'yellow' },
      { pattern = 'word', icon = ' ', color = 'green' },
      { pattern = 'lines', icon = '󰈔', color = 'cyan' },
      { pattern = 'new file', icon = ' ', color = 'cyan' },
      { pattern = 'comment', icon = '󰅺 ', color = 'yellow' },
      { pattern = 'scroll', icon = '󰒺 ', color = 'blue' },
      { pattern = 'move ', icon = '󰆾 ', color = 'blue' },
      { pattern = 'prev', icon = '󰒮 ', color = 'blue' },
      { pattern = 'next', icon = '󰒭 ', color = 'blue' },
      { pattern = 'first', icon = '󰒮 ', color = 'blue' },
      { pattern = 'last', icon = '󰒭 ', color = 'blue' },
      { pattern = 'increase', icon = '󰐕 ', color = 'green' },
      { pattern = 'decrease', icon = '󰍴 ', color = 'red' },
      { pattern = 'focus', icon = ' ', color = 'blue' },
      { pattern = 'redraw', icon = '󰑓 ', color = 'cyan' },
      { pattern = 'escape', icon = '󱊷 ', color = 'red' },
      { pattern = 'exit', icon = '󰈆 ', color = 'red' },
      { pattern = 'list', icon = '󱖫 ', color = 'green' },
      { pattern = 'trouble', icon = '󰔫 ', color = 'red' },
      { pattern = 'markdown', icon = ' ', color = 'blue' },
      { pattern = 'hover', icon = '󰋽 ', color = 'blue' },
      { pattern = 'restore', icon = ' ', color = 'azure' },
      { pattern = 'select session', icon = ' ', color = 'azure' },
      { pattern = 'don.?t save', icon = ' ', color = 'azure' },
      { pattern = 'do not save', icon = ' ', color = 'azure' },
      { pattern = 'zoom', icon = '󰍉 ', color = 'yellow' },
      { pattern = 'zen', icon = '󱅻 ', color = 'cyan' },
      { pattern = 'dim', icon = '󰃤 ', color = 'yellow' },
      { pattern = 'animate', icon = '󰐱 ', color = 'yellow' },
      { pattern = 'indent', icon = '󰉶 ', color = 'cyan' },
      { pattern = 'spelling', icon = '󰓆 ', color = 'yellow' },
      { pattern = 'wrap', icon = '󰖶 ', color = 'yellow' },
      { pattern = 'number', icon = '󰎠 ', color = 'yellow' },
      { pattern = 'conceal', icon = '󰈉 ', color = 'yellow' },
      { pattern = 'tabline', icon = '󰓩 ', color = 'purple' },
      { pattern = 'treesitter', icon = '󰐅 ', color = 'green' },
      { pattern = 'background', icon = '󰏘 ', color = 'purple' },
      { pattern = 'inlay', icon = '󰔡 ', color = 'yellow' },
    },
  },
  spec = {
    { '<leader>s', group = 'search', mode = { 'n', 'v' } },
    { '<leader>f', group = 'file/find' },
    { '<leader>c', group = 'code' },
    { '<leader>b', group = 'buffer' },
    { '<leader>g', group = 'git' },
    { '<leader>h', group = 'git hunks', mode = { 'n', 'v' } },
    { '<leader>q', group = 'quit/session' },
    { '<leader>p', group = 'pack' },
    { '<leader>x', group = 'diagnostics/quickfix' },
    { '<leader>u', group = 'ui' },
    { '<leader>w', group = 'windows' },
    { 'gr', group = 'LSP Actions', mode = { 'n' }, icon = { icon = ' ', color = 'orange' } },
  },
}

-- Window hydra: loop through <C-w> mappings via which-key
vim.keymap.set('n', '<C-w><space>', function()
  require('which-key').show { keys = '<c-w>', loop = true }
end, { desc = 'Window Hydra Mode (which-key)' })
