# Theme - Dracula
[colors.primary]
background = "#282a36"
foreground = "#f8f8f2"

[colors.cursor]
text = "#44475a"
cursor = "#f8f8f2"

[colors.selection]
text = "#f8f8f2"
background = "#44475a"

[colors.normal]
black   = "#21222c"
red     = "#ff5555"
green   = "#50fa7b"
yellow  = "#f1fa8c"
blue    = "#bd93f9"
magenta = "#ff79c6"
cyan    = "#8be9fd"
white   = "#f8f8f2"

[colors.bright]
black   = "#6272a4"
red     = "#ff6e6e"
green   = "#69ff94"
yellow  = "#ffffa5"
blue    = "#d6acff"
magenta = "#ff92df"
cyan    = "#a4ffff"
white   = "#ffffff"

# Font
[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"

# Window
[window]
padding = { x = 8, y = 8 }
option_as_alt = "Both"
startup_mode = "Windowed"
dimensions = { columns = 160, lines = 45 }

# Terminal
[terminal]
osc52 = "CopyPaste"

[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-D", "-s", "main"]

# Working directory
[general]
working_directory = "/Users/vantuh/projects"

# Keybindings
[keyboard]
bindings = [
  { key = "V", mods = "Control", action = "Paste" },
  { key = "V", mods = "Super", action = "Paste" },
  { key = "C", mods = "Control|Shift", action = "Copy" },
  { key = "N", mods = "Control", action = "CreateNewWindow" },
]
