[general]
import = ["~/.config/alacritty/base.toml"]
working_directory = "/Users/vantuh/projects"

[terminal.shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session", "-A", "-D", "-s", "main"]

[window]
startup_mode = "SimpleFullscreen"

[font]
size = 16.0