[general]
import = ["C:\\Users\\Ivan\\AppData\\Roaming\\alacritty\\base.toml"]

[terminal.shell]
program = "wsl.exe"
args = ["--cd", "~", "--", "/home/linuxbrew/.linuxbrew/bin/herdr"]

[font]
size = 12.0
