# History settings.
HISTSIZE=10000
if [[ ${HERDR_AGENT_CHILD:-} == 1 ]]; then
  HISTFILE=/dev/null
else
  HISTFILE=${HISTFILE:-$HOME/.zsh_history}
fi
SAVEHIST=$HISTSIZE
HISTDUP=erase
setopt APPEND_HISTORY
setopt HIST_IGNORE_DUPS
setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt HIST_IGNORE_SPACE
setopt INC_APPEND_HISTORY
setopt SHARE_HISTORY
