/**
 * Herdr cannot tell that Pi is waiting on an answer: Herdr's Pi integration
 * (herdr-agent-state.ts) reports `blocked` — its "needs attention" state — only
 * when something emits the `herdr:blocked` channel. The questionnaire from
 * `ask_user_question` announces its wait on its own channel, so this forwards
 * that wait and lets Herdr show the blocked state and notify about it.
 *
 * Deliberately not derived from Pi's `ui_prompt_start` / `ui_prompt_end`: those
 * wrap every `ctx.ui` dialog, so merely opening an overlay — the subagents
 * fleet view, a custom panel — would report the pane as blocked and bury the
 * real question.
 *
 * The rpiv channel names are that package's published contract (channel names
 * are immutable, payload changes are append-only), spelled out here because Pi
 * loads every package under its own module root, so an extension in
 * ~/.pi/agent/extensions cannot import
 * `@juicesharp/rpiv-ask-user-question/events`.
 *
 * herdr-agent-state.ts is regenerated by `herdr integration install pi`, which
 * is why this lives beside it instead of inside it.
 */
import type { ExtensionAPI } from '@earendil-works/pi-coding-agent';

const ASK_USER_BLOCKED_EVENT = 'rpiv:ask-user:blocked';
const HERDR_BLOCKED_EVENT = 'herdr:blocked';

/** Herdr shows this as the pane's state text while the questionnaire waits. */
const LABEL = 'Waiting for your answer';

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === 'object' && value !== null;
}

function isBlockedEvent(data: unknown): data is { active: boolean } {
  return isRecord(data) && typeof data.active === 'boolean';
}

export default function (pi: ExtensionAPI) {
  pi.events.on(ASK_USER_BLOCKED_EVENT, (data) => {
    if (!isBlockedEvent(data)) return;
    pi.events.emit(HERDR_BLOCKED_EVENT, { active: data.active, label: LABEL });
  });
}
