/**
 * Herdr shows a Pi pane as `working` for the whole agent turn, including the
 * time Pi spends waiting on a blocking user prompt: the `ask_user_question`
 * questionnaire, a confirmation, a select, an input, the editor. Herdr's own
 * Pi integration (herdr-agent-state.ts) can only report `blocked` — its
 * "needs attention" state — when something emits the `herdr:blocked` channel,
 * so this forwards Pi's `ui_prompt_start` / `ui_prompt_end` pair onto it.
 *
 * Those events wrap every `ctx.ui` dialog Pi awaits, nested prompts included,
 * which is why the mapping is one blocked entry per prompt rather than one per
 * question.
 *
 * herdr-agent-state.ts is regenerated by `herdr integration install pi`, which
 * is why this lives beside it instead of inside it.
 */
import type {
  ExtensionAPI,
  UIPromptEndEvent,
  UIPromptStartEvent,
} from '@earendil-works/pi-coding-agent';

const HERDR_BLOCKED_EVENT = 'herdr:blocked';

/** Prompts without a title — the `custom` kind — still need a state text. */
const FALLBACK_LABEL = 'Waiting for your input';

function labelFor(event: UIPromptStartEvent | UIPromptEndEvent): string {
  const title = event.title?.trim();
  return title ? title : FALLBACK_LABEL;
}

export default function (pi: ExtensionAPI) {
  pi.on('ui_prompt_start', (event) => {
    pi.events.emit(HERDR_BLOCKED_EVENT, {
      active: true,
      label: labelFor(event),
    });
  });

  pi.on('ui_prompt_end', (event) => {
    pi.events.emit(HERDR_BLOCKED_EVENT, {
      active: false,
      label: labelFor(event),
    });
  });
}
