onboarding = false

[theme]
name = "dracula"

[session]
resume_agents_on_restore = true

[keys]
prefix = "ctrl+a"

settings = ""
workspace_picker = "prefix+s"

rename_tab = "prefix+comma"

previous_tab = "shift+left"
next_tab = "shift+right"

focus_pane_left = "alt+left"
focus_pane_right = "alt+right"
focus_pane_up = "alt+up"
focus_pane_down = "alt+down"

split_vertical = "prefix+|"
split_horizontal = "prefix+minus"

[keys.indexed]
tabs = "alt"

[ui]
show_agent_labels_on_pane_borders = true
agent_panel_scope = "all"
prompt_new_tab_name = false

[ui.sidebar.spaces]
row_gap = 1

[ui.sidebar.agents]
row_gap = 1

[[keys.command]]
key = "prefix+u"
type = "plugin_action"
command = "vantuh.my-usage.show"
description = "show codex/kiro/cursor usage"

[[keys.command]]
key = "prefix+m"
type = "plugin_action"
command = "vantuh.nvim-cheatsheet.show"
description = "show nvim/lazyvim cheatsheet"

[ui.toast]
delivery = "system"
